on:
  pull_request:
  push:
    branches:
      - dev
  
jobs:
  setup:
    name: Install, Test and Build
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Toolchain
        run: yarn add global @aws-amplify/cli
      - name: Install
        run: yarn install
      - name: Pull dev
        run: amplify pull dev