on:
  push:
    branches:
    - e/amplify-to-terraform
    - dev

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline.yaml
    with:
      ENV: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
