on:
  push:
    branches:
      - c/s3-for-frontend
      - e/amplify-to-terraform
  
jobs:
  setup:
    name: Pipeline
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install Toolchain
        run: |
          sudo apt-get update -y
          sudo apt-get install git -y
      - name: Install
        run: yarn --frozen-lockfile
      - name: Build
        run: PUBLIC_URL=/static-${{ github.sha }} COMMIT_HASH=${{ github.sha }} yarn run build
      - name: Push Backend Code
        run: COMMIT_HASH=${{ github.sha }} bash ./scripts/backend/deploy-lambda.sh
      - name: Push Frontend Code
        run: COMMIT_HASH=${{ github.sha }} bash ./scripts/frontend/deploy-frontend.sh
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Setup Terraform Workspace
        run: terraform init && terraform workspace list && terraform workspace select dev
        working-directory: ./infra
      - name: Deploy
        run: TF_VAR_env=dev TF_VAR_commit_hash=${{ github.sha }} terraform apply --auto-approve
        working-directory: ./infra




