on:
  pull_request:
  push:
    branches:
      - master
  
jobs:
  setup:
    name: Pipeline
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Toolchain
        run: npm install -g @aws-amplify/cli@7.6.4
      - name: Install
        run: yarn install
      - name: Pull dev
        run: sh ./scripts/ci-amplify-init.sh
        env:
          ENV: dev
      # - name: Pull qa
      #   run: sh ./scripts/ci-amplify-init.sh
      #   if: github.ref_name == 'qa'
      #   env:
      #     ENV: qa
      # - name: Pull prod
      #   run: sh ./scripts/ci-amplify-init.sh
      #   if: github.ref_name == 'master'
      #   env:
      #     ENV: prod
      - name: Build
        run: yarn run build
      - name: Publish dev
        run: sh ./scripts/ci-amplify-publish.sh
        env:
          ENV: dev