on:
  push:
    branches:
      - dev
  
jobs:
  setup:
    name: Pipeline
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Toolchain
        run: |
          apk add git
          npm install -g @aws-amplify/cli@7.6.4
      - name: ls
        run: ls -al
      - name: Git Log
        run: git log
      - name: Install
        run: yarn install
      - name: Pull environment
        run: sh ./scripts/ci-amplify-init.sh
        env:
          ENV: ${{ github.ref_name }}
      - name: Build
        run: yarn run build
      - name: Deploy
        run: sh ./scripts/ci-amplify-publish.sh
      - name: Force commit amplify modifications
        uses: EndBug/add-and-commit@v8
        with:
          default_author: github_actions
          message: Post-deployment Amplify modifications to ${{ github.ref_name }}
          push: origin ${{ github.ref_name }} --force
